package tech.amereta.generator.service.spring.generator.module.security;

import tech.amereta.core.java.JavaCompilationUnit;
import tech.amereta.core.java.JavaTypeDeclaration;
import tech.amereta.core.java.declaration.JavaFieldDeclaration;
import tech.amereta.core.java.declaration.JavaMethodDeclaration;
import tech.amereta.core.java.expression.*;
import tech.amereta.core.java.expression.util.JavaMethodInvoke;
import tech.amereta.core.java.statement.JavaControlStatement;
import tech.amereta.core.java.statement.JavaDeclarationStatement;
import tech.amereta.core.java.statement.JavaExpressionStatement;
import tech.amereta.core.java.statement.JavaReturnStatement;
import tech.amereta.core.java.util.JavaAnnotation;
import tech.amereta.core.java.util.JavaModifier;
import tech.amereta.core.java.util.JavaType;
import tech.amereta.generator.service.spring.AbstractSpringSourceCodeGenerator;
import tech.amereta.generator.util.StringFormatter;
import tech.amereta.lang.description.spring.SpringBootApplicationDescription;
import tech.amereta.lang.description.spring.model.type.SpringModelModuleDomainTypeDescription;

import java.lang.reflect.Modifier;
import java.util.List;

public final class AuthenticableUserDetailsServiceGenerator extends AbstractSpringSourceCodeGenerator {

    private static final String CLASS_NAME = "AuthenticableUserDetailsService";

    public static JavaCompilationUnit generate(final SpringBootApplicationDescription applicationDescription) {
        final SpringModelModuleDomainTypeDescription authenticableDomain = getAuthenticableDomain(applicationDescription);
        final String repositoryName = authenticableDomain.getName().toLowerCase() + "Repository";

        return JavaCompilationUnit.builder()
                .packageName(basePackage(applicationDescription) + ".security")
                .name(CLASS_NAME)
                .typeDeclarations(
                        List.of(
                                JavaTypeDeclaration.builder()
                                        .type(JavaType.CLASS)
                                        .name(CLASS_NAME)
                                        .modifiers(
                                                JavaModifier.builder()
                                                        .type(JavaModifier.TYPE_MODIFIERS)
                                                        .modifiers(Modifier.PUBLIC)
                                        )
                                        .implementedClassName("org.springframework.security.core.userdetails.UserDetailsService")
                                        .annotations(
                                                List.of(
                                                        JavaAnnotation.builder()
                                                                .name("org.springframework.stereotype.Component")
                                                                .attributes(
                                                                        List.of(
                                                                                JavaAnnotation.Attribute.builder()
                                                                                        .dataType(String.class)
                                                                                        .values(List.of("userDetailsService"))
                                                                        )
                                                                ),
                                                        JavaAnnotation.builder()
                                                                .name("lombok.extern.slf4j.Slf4j")
                                                )
                                        )
                                        .fieldDeclarations(
                                                List.of(
                                                        JavaFieldDeclaration.builder()
                                                                .name("USER_NOT_FOUND_EXCEPTION")
                                                                .dataType("String")
                                                                .modifiers(
                                                                        JavaModifier.builder()
                                                                                .type(JavaModifier.FIELD_MODIFIERS)
                                                                                .modifiers(Modifier.PRIVATE | Modifier.FINAL | Modifier.STATIC)
                                                                )
                                                                .value("Customer %S was not found in the database"),
                                                        JavaFieldDeclaration.builder()
                                                                .name(repositoryName)
                                                                .dataType(basePackage(applicationDescription) + ".repository." + StringFormatter.toPascalCase(authenticableDomain.getName()) + "Repository")
                                                                .modifiers(
                                                                        JavaModifier.builder()
                                                                                .type(JavaModifier.FIELD_MODIFIERS)
                                                                                .modifiers(Modifier.PRIVATE)
                                                                )
                                                                .annotations(
                                                                        List.of(
                                                                                JavaAnnotation.builder()
                                                                                        .name("org.springframework.beans.factory.annotation.Autowired")
                                                                        )
                                                                )
                                                )
                                        )
                                        .methodDeclarations(
                                                List.of(
                                                        loadByUsernameMethod(),
                                                        loadUserDetailsByEmailMethod(authenticableDomain.getName(), repositoryName),
                                                        loadUserDetailsByUsernameMethod(authenticableDomain.getName(), repositoryName),
                                                        buildUserDetailsMethod(applicationDescription, authenticableDomain.getName())
                                                )
                                        )
                        )
                );
    }

    private static JavaMethodDeclaration loadByUsernameMethod() {
        return JavaMethodDeclaration.builder()
                .name("loadUserByUsername")
                .modifiers(
                        JavaModifier.builder()
                                .type(JavaModifier.METHOD_MODIFIERS)
                                .modifiers(Modifier.PUBLIC)
                )
                .returnType("org.springframework.security.core.userdetails.UserDetails")
                .parameters(
                        List.of(
                                JavaMethodDeclaration.Parameter.builder()
                                        .type("String")
                                        .name("username")
                        )
                )
                .annotations(
                        List.of(
                                JavaAnnotation.builder()
                                        .name("Override"),
                                JavaAnnotation.builder()
                                        .name("org.springframework.transaction.annotation.Transactional")
                                        .attributes(
                                                List.of(
                                                        JavaAnnotation.Attribute.builder()
                                                                .name("readOnly")
                                                                .dataType(Boolean.class)
                                                                .values(List.of("true"))
                                                )
                                        )
                        )
                )
                .exceptions(List.of("org.springframework.security.core.userdetails.UsernameNotFoundException"))
                .statements(
                        List.of(
                                JavaExpressionStatement.builder()
                                        .expression(
                                                JavaMethodInvocationExpression.builder()
                                                        .target("log")
                                                        .invokes(
                                                                List.of(
                                                                        JavaMethodInvoke.builder()
                                                                                .method("debug")
                                                                                .arguments(
                                                                                        List.of(
                                                                                                JavaValueExpression.builder()
                                                                                                        .value("Authenticating {}")
                                                                                                        .type(String.class),
                                                                                                JavaVariableExpression.builder()
                                                                                                        .variable("username")
                                                                                        )
                                                                                )
                                                                )
                                                        )
                                        ),
                                JavaControlStatement.builder()
                                        .ifs(
                                                List.of(
                                                        JavaControlStatement.If.builder()
                                                                .condition(
                                                                        JavaBraceletExpression.builder()
                                                                                .bracelet(false)
                                                                                .expressions(
                                                                                        List.of(
                                                                                                JavaMethodInvocationExpression.builder()
                                                                                                        .target("tech.amereta.starter.jwt.utils.StringUtils")
                                                                                                        .invokes(
                                                                                                                List.of(
                                                                                                                        JavaMethodInvoke.builder()
                                                                                                                                .method("isValidEmail")
                                                                                                                                .arguments(
                                                                                                                                        List.of(
                                                                                                                                                JavaVariableExpression.builder()
                                                                                                                                                        .variable("username")
                                                                                                                                        )
                                                                                                                                )
                                                                                                                )
                                                                                                        )
                                                                                        )
                                                                                )
                                                                )
                                                                .statements(
                                                                        List.of(
                                                                                JavaReturnStatement.builder()
                                                                                        .expression(
                                                                                                JavaMethodInvocationExpression.builder()
                                                                                                        .target("this")
                                                                                                        .invokes(
                                                                                                                List.of(
                                                                                                                        JavaMethodInvoke.builder()
                                                                                                                                .method("loadUserDetailsByEmail")
                                                                                                                                .arguments(
                                                                                                                                        List.of(
                                                                                                                                                JavaVariableExpression.builder()
                                                                                                                                                        .variable("username")
                                                                                                                                        )
                                                                                                                                )
                                                                                                                )
                                                                                                        )
                                                                                        )
                                                                        )
                                                                )
                                                )
                                        ),
                                JavaReturnStatement.builder()
                                        .expression(
                                                JavaMethodInvocationExpression.builder()
                                                        .target("this")
                                                        .invokes(
                                                                List.of(
                                                                        JavaMethodInvoke.builder()
                                                                                .method("loadUserDetailsByUsername")
                                                                                .arguments(
                                                                                        List.of(
                                                                                                JavaVariableExpression.builder()
                                                                                                        .variable("username")
                                                                                        )
                                                                                )
                                                                )
                                                        )
                                        )
                        )
                );
    }

    private static JavaMethodDeclaration loadUserDetailsByEmailMethod(String domainName, String repositoryName) {
        return JavaMethodDeclaration.builder()
                .name("loadUserDetailsByEmail")
                .modifiers(
                        JavaModifier.builder()
                                .type(JavaModifier.METHOD_MODIFIERS)
                                .modifiers(Modifier.PUBLIC)
                )
                .returnType("org.springframework.security.core.userdetails.UserDetails")
                .parameters(
                        List.of(
                                JavaMethodDeclaration.Parameter.builder()
                                        .modifiers(
                                                JavaModifier.builder()
                                                        .type(JavaModifier.FIELD_MODIFIERS)
                                                        .modifiers(Modifier.FINAL)
                                        )
                                        .type("String")
                                        .name("username")
                        )
                )
                .statements(
                        List.of(
                                JavaReturnStatement.builder()
                                        .expression(
                                                JavaMethodInvocationExpression.builder()
                                                        .target(repositoryName)
                                                        .invokes(
                                                                List.of(
                                                                        JavaMethodInvoke.builder()
                                                                                .method("findOneByEmailIgnoreCase")
                                                                                .arguments(
                                                                                        List.of(
                                                                                                JavaVariableExpression.builder()
                                                                                                        .variable("username")
                                                                                        )
                                                                                ),
                                                                        JavaMethodInvoke.builder()
                                                                                .method("map")
                                                                                .arguments(
                                                                                        List.of(
                                                                                                JavaLambdaExpression.builder()
                                                                                                        .consumer(List.of(domainName.toLowerCase()))
                                                                                                        .statements(
                                                                                                                List.of(
                                                                                                                        JavaReturnStatement.builder()
                                                                                                                                .expression(
                                                                                                                                        JavaMethodInvocationExpression.builder()
                                                                                                                                                .target("this")
                                                                                                                                                .invokes(
                                                                                                                                                        List.of(
                                                                                                                                                                JavaMethodInvoke.builder()
                                                                                                                                                                        .method("buildUserDetails")
                                                                                                                                                                        .arguments(
                                                                                                                                                                                List.of(
                                                                                                                                                                                        JavaVariableExpression.builder()
                                                                                                                                                                                                .variable(domainName.toLowerCase()),
                                                                                                                                                                                        JavaVariableExpression.builder()
                                                                                                                                                                                                .variable("username")
                                                                                                                                                                                )
                                                                                                                                                                        )
                                                                                                                                                        )
                                                                                                                                                )
                                                                                                                                )
                                                                                                                )
                                                                                                        )
                                                                                        )
                                                                                ),
                                                                        JavaMethodInvoke.builder()
                                                                                .method("orElseThrow")
                                                                                .arguments(
                                                                                        List.of(
                                                                                                JavaLambdaExpression.builder()
                                                                                                        .consumer(List.of())
                                                                                                        .statements(
                                                                                                                List.of(
                                                                                                                        JavaExpressionStatement.builder()
                                                                                                                                .expression(
                                                                                                                                        JavaThrowExpression.builder()
                                                                                                                                                .name("org.springframework.security.core.userdetails.UsernameNotFoundException")
                                                                                                                                                .arguments(
                                                                                                                                                        List.of(
                                                                                                                                                                JavaMethodInvocationExpression.builder()
                                                                                                                                                                        .target("String")
                                                                                                                                                                        .invokes(
                                                                                                                                                                                List.of(
                                                                                                                                                                                        JavaMethodInvoke.builder()
                                                                                                                                                                                                .method("format")
                                                                                                                                                                                                .arguments(
                                                                                                                                                                                                        List.of(
                                                                                                                                                                                                                JavaVariableExpression.builder()
                                                                                                                                                                                                                        .variable("USER_NOT_FOUND_EXCEPTION"),
                                                                                                                                                                                                                JavaVariableExpression.builder()
                                                                                                                                                                                                                        .variable("username")
                                                                                                                                                                                                        )
                                                                                                                                                                                                )
                                                                                                                                                                                )
                                                                                                                                                                        )
                                                                                                                                                        )
                                                                                                                                                )
                                                                                                                                )
                                                                                                                )
                                                                                                        )
                                                                                        )
                                                                                )
                                                                )
                                                        )
                                        )
                        )
                );
    }

    private static JavaMethodDeclaration loadUserDetailsByUsernameMethod(String domainName, String repositoryName) {
        return JavaMethodDeclaration.builder()
                .name("loadUserDetailsByUsername")
                .modifiers(
                        JavaModifier.builder()
                                .type(JavaModifier.METHOD_MODIFIERS)
                                .modifiers(Modifier.PUBLIC)
                )
                .returnType("org.springframework.security.core.userdetails.UserDetails")
                .parameters(
                        List.of(
                                JavaMethodDeclaration.Parameter.builder()
                                        .modifiers(
                                                JavaModifier.builder()
                                                        .type(JavaModifier.FIELD_MODIFIERS)
                                                        .modifiers(Modifier.FINAL)
                                        )
                                        .type("String")
                                        .name("username")
                        )
                )
                .statements(
                        List.of(
                                JavaReturnStatement.builder()
                                        .expression(
                                                JavaMethodInvocationExpression.builder()
                                                        .target(repositoryName)
                                                        .invokes(
                                                                List.of(
                                                                        JavaMethodInvoke.builder()
                                                                                .method("findOneByUsername")
                                                                                .arguments(
                                                                                        List.of(
                                                                                                JavaMethodInvocationExpression.builder()
                                                                                                        .target("username")
                                                                                                        .invokes(
                                                                                                                List.of(
                                                                                                                        JavaMethodInvoke.builder()
                                                                                                                                .method("toLowerCase")
                                                                                                                )
                                                                                                        )
                                                                                        )
                                                                                ),
                                                                        JavaMethodInvoke.builder()
                                                                                .method("map")
                                                                                .arguments(
                                                                                        List.of(
                                                                                                JavaLambdaExpression.builder()
                                                                                                        .consumer(List.of(domainName.toLowerCase()))
                                                                                                        .statements(
                                                                                                                List.of(
                                                                                                                        JavaReturnStatement.builder()
                                                                                                                                .expression(
                                                                                                                                        JavaMethodInvocationExpression.builder()
                                                                                                                                                .target("this")
                                                                                                                                                .invokes(
                                                                                                                                                        List.of(
                                                                                                                                                                JavaMethodInvoke.builder()
                                                                                                                                                                        .method("buildUserDetails")
                                                                                                                                                                        .arguments(
                                                                                                                                                                                List.of(
                                                                                                                                                                                        JavaVariableExpression.builder()
                                                                                                                                                                                                .variable(domainName.toLowerCase()),
                                                                                                                                                                                        JavaVariableExpression.builder()
                                                                                                                                                                                                .variable("username")
                                                                                                                                                                                )
                                                                                                                                                                        )
                                                                                                                                                        )
                                                                                                                                                )
                                                                                                                                )
                                                                                                                )
                                                                                                        )
                                                                                        )
                                                                                ),
                                                                        JavaMethodInvoke.builder()
                                                                                .method("orElseThrow")
                                                                                .arguments(
                                                                                        List.of(
                                                                                                JavaLambdaExpression.builder()
                                                                                                        .consumer(List.of())
                                                                                                        .statements(
                                                                                                                List.of(
                                                                                                                        JavaExpressionStatement.builder()
                                                                                                                                .expression(
                                                                                                                                        JavaThrowExpression.builder()
                                                                                                                                                .name("org.springframework.security.core.userdetails.UsernameNotFoundException")
                                                                                                                                                .arguments(
                                                                                                                                                        List.of(
                                                                                                                                                                JavaMethodInvocationExpression.builder()
                                                                                                                                                                        .target("String")
                                                                                                                                                                        .invokes(
                                                                                                                                                                                List.of(
                                                                                                                                                                                        JavaMethodInvoke.builder()
                                                                                                                                                                                                .method("format")
                                                                                                                                                                                                .arguments(
                                                                                                                                                                                                        List.of(
                                                                                                                                                                                                                JavaVariableExpression.builder()
                                                                                                                                                                                                                        .variable("USER_NOT_FOUND_EXCEPTION"),
                                                                                                                                                                                                                JavaVariableExpression.builder()
                                                                                                                                                                                                                        .variable("username")
                                                                                                                                                                                                        )
                                                                                                                                                                                                )
                                                                                                                                                                                )
                                                                                                                                                                        )
                                                                                                                                                        )
                                                                                                                                                )
                                                                                                                                )
                                                                                                                )
                                                                                                        )
                                                                                        )
                                                                                )
                                                                )
                                                        )
                                        )
                        )
                );
    }

    private static JavaMethodDeclaration buildUserDetailsMethod(SpringBootApplicationDescription applicationDescription, String domainName) {
        return JavaMethodDeclaration.builder()
                .name("buildUserDetails")
                .modifiers(
                        JavaModifier.builder()
                                .type(JavaModifier.METHOD_MODIFIERS)
                                .modifiers(Modifier.PUBLIC)
                )
                .returnType("org.springframework.security.core.userdetails.UserDetails")
                .parameters(
                        List.of(
                                JavaMethodDeclaration.Parameter.builder()
                                        .modifiers(
                                                JavaModifier.builder()
                                                        .type(JavaModifier.FIELD_MODIFIERS)
                                                        .modifiers(Modifier.FINAL)
                                        )
                                        .type(basePackage(applicationDescription) + ".model.domain." + StringFormatter.toPascalCase(domainName))
                                        .name(domainName.toLowerCase()),
                                JavaMethodDeclaration.Parameter.builder()
                                        .modifiers(
                                                JavaModifier.builder()
                                                        .type(JavaModifier.FIELD_MODIFIERS)
                                                        .modifiers(Modifier.FINAL)
                                        )
                                        .type("String")
                                        .name("username")
                        )
                )
                .statements(
                        List.of(
                                JavaDeclarationStatement.builder()
                                        .name("authorities")
                                        .dataType("java.util.List")
                                        .genericTypes(List.of("org.springframework.security.core.GrantedAuthority"))
                                        .modifiers(
                                                JavaModifier.builder()
                                                        .type(JavaModifier.FIELD_MODIFIERS)
                                                        .modifiers(Modifier.FINAL)
                                        )
                                        .initialized(true)
                                        .expression(
                                                JavaMethodInvocationExpression.builder()
                                                        .target(domainName.toLowerCase())
                                                        .invokes(
                                                                List.of(
                                                                        JavaMethodInvoke.builder()
                                                                                .method("getRoles")
                                                                                .breakLine(true),
                                                                        JavaMethodInvoke.builder()
                                                                                .method("stream")
                                                                                .breakLine(true),
                                                                        JavaMethodInvoke.builder()
                                                                                .method("map")
                                                                                .arguments(
                                                                                        List.of(
                                                                                                JavaLambdaMethodInvocationExpression.builder()
                                                                                                        .target(basePackage(applicationDescription) + ".model.enumeration.Role")
                                                                                                        .invoke("toString")
                                                                                        )
                                                                                )
                                                                                .breakLine(true),
                                                                        JavaMethodInvoke.builder()
                                                                                .method("map")
                                                                                .arguments(
                                                                                        List.of(
                                                                                                JavaLambdaMethodInvocationExpression.builder()
                                                                                                        .target("org.springframework.security.core.authority.SimpleGrantedAuthority")
                                                                                                        .invoke("new")
                                                                                        )
                                                                                )
                                                                                .breakLine(true),
                                                                        JavaMethodInvoke.builder()
                                                                                .method("collect")
                                                                                .arguments(
                                                                                        List.of(
                                                                                                JavaMethodInvocationExpression.builder()
                                                                                                        .target("java.util.stream.Collectors")
                                                                                                        .invokes(
                                                                                                                List.of(
                                                                                                                        JavaMethodInvoke.builder()
                                                                                                                                .method("toList")
                                                                                                                )
                                                                                                        )
                                                                                        )
                                                                                )
                                                                                .breakLine(true)
                                                                )
                                                        )
                                        ),
                                JavaReturnStatement.builder()
                                        .expression(
                                                JavaNewInstanceExpression.builder()
                                                        .name("org.springframework.security.core.userdetails.User")
                                                        .arguments(
                                                                List.of(
                                                                        JavaVariableExpression.builder()
                                                                                .variable("username"),
                                                                        JavaMethodInvocationExpression.builder()
                                                                                .target(domainName.toLowerCase())
                                                                                .invokes(
                                                                                        List.of(
                                                                                                JavaMethodInvoke.builder()
                                                                                                        .method("getPassword")
                                                                                        )
                                                                                ),
                                                                        JavaVariableExpression.builder()
                                                                                .variable("authorities")
                                                                )
                                                        )
                                        )
                        )
                );
    }
}
