package tech.amereta.core.domain.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import tech.amereta.core.service.web.SpringBootGeneratorService;

import javax.validation.constraints.NotNull;

@Builder
@Data
@AllArgsConstructor
@NoArgsConstructor
public class SpringBootApplication implements Application {

    @NotNull
    private String name;

    @Builder.Default
    private String description = "Generated by Amereta!";

    @Builder.Default
    private String javaVersion = "17";

    @Builder.Default
    private String springVersion = "3.1.3";

    @Builder.Default
    private String port = "8080";

    @Builder.Default
    @JsonIgnore
    private Class<?> generator = SpringBootGeneratorService.class;
}
