package tech.amereta.generator.service.generator.spring.main;

import tech.amereta.generator.domain.description.SpringBootApplicationDescription;
import tech.amereta.generator.service.generator.spring.AbstractSpringSourceCodeGenerator;
import tech.amereta.generator.util.code.java.source.JavaCompilationUnit;
import tech.amereta.generator.util.code.java.source.JavaTypeDeclaration;
import tech.amereta.generator.util.code.java.util.JavaAnnotation;
import tech.amereta.generator.util.code.java.util.JavaModifier;
import tech.amereta.generator.util.code.java.util.JavaType;

import java.lang.reflect.Modifier;
import java.util.List;

public final class AmeretaAnnotationGeneratorSpring extends AbstractSpringSourceCodeGenerator {

    public static JavaCompilationUnit generate(final SpringBootApplicationDescription applicationDescription) {
        return JavaCompilationUnit.builder()
                .packageName(basePackage(applicationDescription))
                .name("GeneratedByAmereta")
                .typeDeclarations(List.of(
                        JavaTypeDeclaration.builder()
                                .type(JavaType.ANNOTATION)
                                .name("GeneratedByAmereta")
                                .modifiers(JavaModifier.builder()
                                        .type(JavaModifier.TYPE_MODIFIERS)
                                        .modifiers(Modifier.PUBLIC)
                                        .build())
                                .annotations(List.of(
                                        JavaAnnotation.builder()
                                                .name("javax.annotation.Generated")
                                                .attributes(List.of(
                                                        JavaAnnotation.Attribute.builder()
                                                                .name("value")
                                                                .type(String.class)
                                                                .values(List.of("Amereta"))
                                                                .build(),
                                                        JavaAnnotation.Attribute.builder()
                                                                .name("comments")
                                                                .type(String.class)
                                                                .values(List.of("Generated By Amereta!"))
                                                                .build()))
                                                .build(),
                                        JavaAnnotation.builder()
                                                .name("java.lang.annotation.Retention")
                                                .attributes(List.of(
                                                        JavaAnnotation.Attribute.builder()
                                                                .name("value")
                                                                .type(Enum.class)
                                                                .values(List.of("java.lang.annotation.RetentionPolicy.SOURCE"))
                                                                .build()))
                                                .build(),
                                        JavaAnnotation.builder()
                                                .name("java.lang.annotation.Target")
                                                .attributes(List.of(
                                                        JavaAnnotation.Attribute.builder()
                                                                .name("value")
                                                                .type(Enum.class)
                                                                .values(List.of("java.lang.annotation.ElementType.TYPE"))
                                                                .build()))
                                                .build()))
                                .build()))
                .build();
    }
}
