package tech.amereta.generator.service.spring.main;

import tech.amereta.generator.domain.description.SpringBootApplicationDescription;
import tech.amereta.generator.service.spring.AbstractSpringSourceCodeGenerator;
import tech.amereta.core.java.JavaCompilationUnit;
import tech.amereta.core.java.JavaTypeDeclaration;
import tech.amereta.core.java.util.JavaAnnotation;
import tech.amereta.core.java.util.JavaModifier;
import tech.amereta.core.java.util.JavaType;

import java.lang.reflect.Modifier;
import java.util.List;

public final class AmeretaAnnotationGeneratorSpring extends AbstractSpringSourceCodeGenerator {

    public static JavaCompilationUnit generate(final SpringBootApplicationDescription applicationDescription) {
        return JavaCompilationUnit.builder()
                .packageName(basePackage(applicationDescription))
                .name("GeneratedByAmereta")
                .typeDeclarations(List.of(
                        JavaTypeDeclaration.builder()
                                .type(JavaType.ANNOTATION)
                                .name("GeneratedByAmereta")
                                .modifiers(JavaModifier.builder()
                                        .type(JavaModifier.TYPE_MODIFIERS)
                                        .modifiers(Modifier.PUBLIC))
                                .annotations(List.of(
                                        JavaAnnotation.builder()
                                                .name("jakarta.annotation.Generated")
                                                .attributes(List.of(
                                                        JavaAnnotation.Attribute.builder()
                                                                .name("value")
                                                                .dataType(String.class)
                                                                .values(List.of("Amereta")),
                                                        JavaAnnotation.Attribute.builder()
                                                                .name("comments")
                                                                .dataType(String.class)
                                                                .values(List.of("Generated By Amereta!")))),
                                        JavaAnnotation.builder()
                                                .name("java.lang.annotation.Retention")
                                                .attributes(List.of(
                                                        JavaAnnotation.Attribute.builder()
                                                                .name("value")
                                                                .dataType(Enum.class)
                                                                .values(List.of("java.lang.annotation.RetentionPolicy.SOURCE")))),
                                        JavaAnnotation.builder()
                                                .name("java.lang.annotation.Target")
                                                .attributes(List.of(
                                                        JavaAnnotation.Attribute.builder()
                                                                .name("value")
                                                                .dataType(Enum.class)
                                                                .values(List.of("java.lang.annotation.ElementType.TYPE"))))))));
    }
}
